# Generated by Django 3.0.7 on 2020-06-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourceCode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.TextField(),
        ),
    ]
