# Generated by Django 3.0.7 on 2020-06-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourceCode', '0002_auto_20200612_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
